import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useState} from 'react'

export default function Home() {
  const [count, setCount] = useState(0)
  const [ todolist, setTodoList] = useState(["a", "b", "c", "d"])
  const [addTodo, setAddTodo] = useState('')
  const [disabled, setDisabled] = useState(true)
  const [editabledTodo, setEditabledTodo] = useState(null)
  
  const editTask = (item, index) => {
    setEditabledTodo(index)
  }

  const hanleChange = e => {
    let newTodoList = [...todolist]
    newTodoList[editabledTodo] = e.target.value
    setTodoList(newTodoList)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <h1>Hello</h1>
       <h3>Count : {count}</h3>
       <button onClick={() => setCount(prev => prev + 1)}>Click</button>

      {/* i > 1 ? true : false
          i > 1 && true  */}
      
      <input onChange={ (e) => setAddTodo(addTodo => e.target.value) }></input>
      <button onClick={()=> setTodoList( todolist => [...todolist, addTodo])}>Add task</button>


       { todolist.length > 0 && (
         todolist.map((todo, i) => {
           return (
             <div  key={i}>
              <input type="text" onChange={(e) => hanleChange(e)} defaultValue={todo} disabled={editabledTodo === i ? false : true}/>

              <button onClick={() =>
              editTask(todo, i)
              }>Change</button>

              <button onClick={() =>
              setTodoList(prevArray => prevArray.filter( (item, index) => index !==i))
              }>Delete</button>

           </div>
           )
         })
       )}
      </main>

    </div>
  )
}
