import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useState, useEffect} from 'react'
import { useRouter } from 'next/router'
import Card from '../components/Card'

export default function Home() {
  const [count, setCount] = useState(0)
  const [ todolist, setTodoList] = useState(["a", "b", "c", "d"])
  const [addTodo, setAddTodo] = useState('')
  const [editabledTodo, setEditabledTodo] = useState(null)
  const [color, setColor] = useState('#fff')
  const [cardList, setCardList] = useState([
    ['titre', 'dec', '30', 'https://images.unsplash.com/photo-1639502496516-95531e23e304?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=465&q=80'],
    ['titre-2', 'decscription', '20', 'https://images.unsplash.com/photo-1639502496516-95531e23e304?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=465&q=80'],
    ['titre-2', 'decscription', '20', 'https://images.unsplash.com/photo-1639502496516-95531e23e304?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=465&q=80'],
    ['titre-2', 'decscription', '20', 'https://images.unsplash.com/photo-1639502496516-95531e23e304?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=465&q=80'],
    ['titre-2', 'decscription', '20', 'https://images.unsplash.com/photo-1639502496516-95531e23e304?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=465&q=80'],
  ])

  const editTask = (item, index) => {
    setEditabledTodo(index)
  }

  const hanleChange = e => {
    let newTodoList = [...todolist]
    newTodoList[editabledTodo] = e.target.value
    setTodoList(newTodoList)
  }

  useEffect(()=> {
    console.log("modification")
  }, [todolist]);

  useEffect(()=> {
    count >= 1 && setColor('#222')
  }, [count]);

  useEffect(()=> {
    localStorage.setItem("todos", todolist)
    return () => {
      localStorage.clear()
    }
  }, [todolist]);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <h1>Hello</h1>
       <h3>Count : {count}</h3>
       <button style={{ backgroundColor : color}} onClick={() => setCount(prev => prev + 1)}>Click</button>

      {/* i > 1 ? true : false
          i > 1 && true  */}
      
      <input onChange={ (e) => setAddTodo(addTodo => e.target.value) }></input>
      <button onClick={()=> setTodoList( todolist => [...todolist, addTodo])}>Add task</button>


       { todolist.length > 0 && (
         todolist.map((todo, i) => {
           return (
             <div  key={i}>
              <input type="text" onChange={(e) => hanleChange(e)} defaultValue={todo} disabled={editabledTodo === i ? false : true}/>

              <button onClick={() =>
              editTask(todo, i)
              }>Change</button>

              <button onClick={() =>
              setTodoList(prevArray => prevArray.filter( (item, index) => index !==i))
              }>Delete</button>

           </div>
           )
         })
       )}

<div className='allCard'>

  { cardList.length > 0 && (
          cardList.map((card, i) => {
            return (
              <div  key={i}>
                  <Card title={card[0]} desc={card[1]} price={card[2]} image={card[3]} />
            </div>
            )
          })
        )}
</div>
      </main>

    </div>
  )
}
